name: nuxtjs
services:
  node:
    type: node:18
    command: "yarn dev --hostname 0.0.0.0 --port 80"
    install_dependencies_as_me:
      - yarn install
    overrides:
      ports:
        - "24678:24678"
tooling:
  yarn:
    service: node
  npm:
    service: node
  npx:
    service: node
  node:
    service: node
  nuxt:
    cmd: /app/node_modules/.bin/nuxt
    service: node
events:
  pre-start:
    - yarn install
proxy:
  node:
    - nuxtjs.lndo.site
exclude:
  - node_modules